[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
sepolia = "https://optimism-sepolia.api.onfinality.io/public"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
